import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#412d00',
        'on-secondary-fixed': '#251a00',
        'on-primary': '#412d00',
        'inverse-on-surface': '#32302a',
        'on-background': '#e7e2d9',
        'on-tertiary-fixed': '#0e1f13',
        'on-secondary-container': '#e1c38c',
        'surface-container': '#211f1a',
        'primary-fixed': '#ffdf9e',
        'on-secondary': '#3e2e04',
        'surface-variant': '#4e4639',
        'tertiary': '#a8d0b5',
        'tertiary-container': '#274e36',
        'surface-dim': '#14130f',
        'secondary': '#c5a874',
        'primary-fixed-dim': '#f5bc4e',
        'tertiary-fixed-dim': '#a8d0b5',
        'primary-container': '#5e4200',
        'primary': '#f5bc4e',
        'inverse-surface': '#e7e2d9',
        'error': '#ffb4ab',
        'on-surface-variant': '#d1c5b4',
        'surface-tint': '#f5bc4e',
        'error-container': '#93000a',
        'tertiary-fixed': '#c4ecd0',
        'on-surface': '#e7e2d9',
        'secondary-fixed': '#e3c38c',
        'outline': '#9a8f80',
        'surface': '#14130f',
        'background': '#14130f',
        'on-primary-fixed': '#261900',
        'on-secondary-fixed-variant': '#564419',
        'inverse-primary': '#7b5800',
        'outline-variant': '#4e4639',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#5e4200',
        'on-tertiary-container': '#c4ecd0',
        'surface-container-high': '#2c2a24',
        'secondary-container': '#564419',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0f0e0a',
        'on-tertiary': '#143721',
        'on-tertiary-fixed-variant': '#274e36',
        'surface-container-low': '#1d1b16',
        'surface-container-highest': '#37352e',
        'secondary-fixed-dim': '#c5a874',
        'surface-bright': '#3a3934',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'display': ['Playfair Display', 'serif'],
        'headline': ['Playfair Display', 'serif'],
        'title': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
